apiVersion: v1
data:
  currency: USD
  locale: en-US
  taxLabel: Sales Tax
  taxRate: "8"
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
  name: regional-value-store
