apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-config
  namespace: otel-demo
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  otel-collector-name: otel-collector
  otel-exporter-otlp-endpoint-http: http://otel-collector:4318
  otel-exporter-otlp-endpoint-grpc: http://otel-collector:4317
  flagd-otel-collector-uri: otel-collector:4317
  grafana-host: grafana
  jaeger-host: jaeger
