apiVersion: v1
data:
  adImage: ghcr.io/kptdev/kpt-samples/otel-demo/astronomy-ad:v1
  emailImage: ghcr.io/kptdev/kpt-samples/otel-demo/astronomy-email:v1
  frontendImage: ghcr.io/kptdev/kpt-samples/otel-demo/astronomy-frontend:v1
  imageProviderImage: ghcr.io/open-telemetry/demo:2.2.0-image-provider
  llmImage: ghcr.io/kptdev/kpt-samples/otel-demo/astronomy-llm:v1
  llmProductId: L9ECAV7KIM
  loadGeneratorImage: ghcr.io/open-telemetry/demo:2.2.0-load-generator
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
  name: value-store
